### ISSUE TITLE
potato

### ISSUE THREAD

**Issue by RajeInkworks** [openfarmcc/open-crop-icons#19]
I have attached the potato in size of 32, 24, 64
![potato24](https://cloud.githubusercontent.com/assets/10882609/25315741/c98b19ae-2877-11e7-9ea2-0a335b15375e.png)
![potato32](https://cloud.githubusercontent.com/assets/10882609/25315742/c997238e-2877-11e7-8d47-6b5ac57f0381.png)
![potato64](https://cloud.githubusercontent.com/assets/10882609/25315739/c93d3f36-2877-11e7-91ae-42112c922b46.png)

**Comment by RajeInkworks** [comment]
feedback wanted

**Comment by simonv3** [comment]
Awesome, thanks @Rajalashmi, these look great to me.

cc @andru @roryaronson.

**Comment by RajeInkworks** [comment]
thanks @simonv3
