### ISSUE TITLE
yam

### ISSUE THREAD

**Issue by RajeInkworks** [openfarmcc/open-crop-icons#20]
I have started working on yam
![yam24](https://cloud.githubusercontent.com/assets/10882609/25315988/3c41faae-287c-11e7-84f8-e5cd4b0232bc.png)
![yam32](https://cloud.githubusercontent.com/assets/10882609/25315989/3c523c7a-287c-11e7-9f86-e8aad9fa2a7b.png)
![yam64](https://cloud.githubusercontent.com/assets/10882609/25315990/3c643d76-287c-11e7-8a23-2ce064d29209.png)

**Comment by simonv3** [comment]
I would maybe make the black orange here?
