### ISSUE TITLE
How best to contribute 100+ icons

### ISSUE THREAD

**Issue by roryaronson** [openfarmcc/open-crop-icons#21]
Hey all!

I apologize for not posting in this repository sooner, but through my work with [FarmBot](https://farmbot.io) we've been developing a bunch (100+) crop icons and uploading them to OpenFarm directly! While no crop icons are currently used on the OpenFarm interface, you can see them on the crop edit pages:

* https://openfarm.cc/en/crops/cucumber/edit
* https://openfarm.cc/en/crops/potato/edit
* https://openfarm.cc/en/crops/japanese-yam/edit

And you can see all of the icons we've made so far [here](https://drive.google.com/drive/folders/0Bzm0yyP7JMLiM0U4ZkdmNG9rVjQ?usp=sharing). Some have not yet been uploaded to OpenFarm.

I'm thinking these should all be added to this repository too instead of just OpenFarm directly. Is the current organizational scheme still something we want to move forward with? Does hosting these on GitHub really make a lot of sense?

cc: @jsimplicio @neynah @andru @simonv3

**Comment by andru** [comment]
Those icons are sweet af @roryaronson - who did them?

I think GitHub is a good organisational structure for an open set of SVG icons and that way they're in the wild, so to speak :)

**Comment by roryaronson** [comment]
@andru my friend [Claire Dierksen](http://www.clairedierksen.com/)! (no Github account). I've been paying her via FarmBot to create them, and then another friend Katie has been uploading them to OpenFarm and also adding basic crop info for the fields we have. I think there are now over 200 icons made for the most common vegetable crops!

I'm fine putting them up on Github. I just wonder if its the most accessible location for non techies. Another option is to make a page on OpenFarm itself that shows all the icons and offers a bulk download button?

**Comment by Br3nda** [comment]
I've copied Claire's lovely icons into PR here #22
