### ISSUE TITLE
Corn & Pumpkin 

### ISSUE THREAD

**Issue by jsimplicio** [openfarmcc/open-crop-icons#6]
Hey all,

I just got down and did the corn for now. Let me know what you think!

edit: made pumpkin.

![corn](https://cloud.githubusercontent.com/assets/7318958/12471234/3e01a5d0-bfc1-11e5-9196-2823ad9caf3d.png)![pumpkin](https://cloud.githubusercontent.com/assets/7318958/12471659/5dfce4c2-bfc5-11e5-826e-44b06da2a7db.png)
![corn-3x](https://cloud.githubusercontent.com/assets/7318958/12471237/41fefa5c-bfc1-11e5-9202-51f6a3dc8502.png)![pumpkin-3x](https://cloud.githubusercontent.com/assets/7318958/12471665/6792b0de-bfc5-11e5-9750-3982e80c48a1.png)

**Comment by roryaronson** [comment]
Zomg they're both so cute! :+1:

**Comment by andru** [comment]
These look great!  I think the corn could work better in the smaller sizes if the stroke was removed from around the kernals and a contrasting background was behind them.  Something like this...  

![image](https://cloud.githubusercontent.com/assets/30393/12480438/9f23e95a-c042-11e5-9c59-07742c122ca0.png)  ![image](https://cloud.githubusercontent.com/assets/30393/12480597/c31d0570-c043-11e5-82e2-c9108d211b95.png)

Also, maybe a touch lighter for the husk...

![image](https://cloud.githubusercontent.com/assets/30393/12480493/0077ad2c-c043-11e5-84bf-e8543cc5c675.png)

And the other icons place a light source on the left, so the tone of the leaves should be reversed.

Pumkin form is great in the larger image. I think the form for the bottom gets lost when scaled down, so we could try exaggerating it a bit.  Maybe a tiny bit more line contrast so the form renders more clearly in the smaller size? And/or a slight shine on the right facing bits for consistency with the other icons?

**Comment by jsimplicio** [comment]
@andru Awesome feedback! I'm gonna edit them and get back to you later!

**Comment by simonv3** [comment]
These are so cute, thanks for doing this!

**Comment by jsimplicio** [comment]
Hey all here's some updates based on @andru's feedback
![corn](https://cloud.githubusercontent.com/assets/7318958/12495092/755c9e44-c053-11e5-8045-8a90b075205c.png)
![pumpkin](https://cloud.githubusercontent.com/assets/7318958/12495095/78bbbb42-c053-11e5-9034-3025e12fdf76.png)

![corn-3x](https://cloud.githubusercontent.com/assets/7318958/12495103/7dc2aeca-c053-11e5-99c2-fd8d785ab9b2.png)![pumpkin-3x](https://cloud.githubusercontent.com/assets/7318958/12495102/7db02fd4-c053-11e5-89f5-e11363406aa6.png)

**Comment by andru** [comment]
Both are looking great, @jsimplicio!

I'd be tempted to increase the contrast on the corn even more at 24px, but leave it as it is for the larger size.  Also, maybe the lighter corn husk should overlap the darker?

The pumpkin at 24px is awesome. So cute! For the larger one I think you had it right with the stroke colour in your first go.

**Comment by jsimplicio** [comment]
Hey @andru.
Thanks for the feedback.

How is this? Edited at every size.

![screen shot 2016-01-22 at 12 34 13 pm](https://cloud.githubusercontent.com/assets/7318958/12519456/7d929814-c104-11e5-9484-f9f3bb040019.png)

**Comment by andru** [comment]
Pumpkin: super!

Corn: Also super, but we should put the light source on the left for consistency. Flip it and we're done!

Thanks for the sweet work :raised_hands:

**Comment by roryaronson** [comment]
Awesome work everyone :+1: 

It sounds like we should add "light sources should be in the top left of the icon" to the style guide. We could use these corns as a side-by-side example of what is preferred.

**Comment by jsimplicio** [comment]
Hey all!
Fixed the corns and here's a screenshot if we wanna add to style guide the example:
![screen shot 2016-01-22 at 12 49 24 pm](https://cloud.githubusercontent.com/assets/7318958/12519821/9f841af4-c106-11e5-8020-00b3bd6d89af.png)
